using IDS.Core.Fea;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;

namespace IDS.Testing.UnitTests
{
    [DeploymentItem(@"UnitTestData", @"UnitTestData")]
    [TestClass]
    public class InpTests
    {
        [TestMethod]
        public void InpCompareReadWrite()
        {
            var resources = new TestResources();

            var inp = new Inp(resources.InpInputFile);
            inp.Read();
            inp.InpFile = resources.InpOutputfile;
            inp.Write();

            var inputLines = File.ReadAllLines(resources.InpInputFile);
            var outputLines = File.ReadAllLines(resources.InpOutputfile);

            Assert.AreEqual(inputLines.Length, outputLines.Length);

            for (var i = 0; i < inputLines.Length; i++)
            {
                Assert.AreEqual(CleanString(inputLines[i]), CleanString(outputLines[i]), $"Line {i + 1}");
            }
        }

        [TestMethod]
        public void InpWriteSimulation()
        {
            var resources = new TestResources();

            var inpPartNodes = new List<double[]>(10)
            {
                new double[] {42.43426235, 25.42505676, 41.70442496},
                new double[] {-42.19525282, -20.81917594, -48.76340661},
                new double[] {-31.9360429, 8.573834545, -27.81285561},
                new double[] {49.96204622, -39.79744381, 40.43529585},
                new double[] {-49.13838234, 26.10712157, -34.94619258},
                new double[] {-8.733007953, -21.16886775, 33.62122356},
                new double[] {-26.61676015, -22.89478954, -38.24144866},
                new double[] {21.95294674, 15.65370387, -29.30158267},
                new double[] {20.01803393, 0.197912162, -7.193738885},
                new double[] {-4.183780198, -41.24767139, -3.688948005}
            };

            var inpPartElements = new List<int[]>(10)
            {
                new int[] {30, 99, 82},
                new int[] {37, 86, 91},
                new int[] {36, 27, 13},
                new int[] {32, 79, 78},
                new int[] {33, 67, 84},
                new int[] {45, 27, 9},
                new int[] {41, 78, 87},
                new int[] {94, 98, 5},
                new int[] {84, 75, 95},
                new int[] {88, 51, 42}
            };

            const string inpPartName = "partname";
            const string inpPartElementsName = "elementsname";
            const string inpPartElementType = "elementtype";

            const double loadMagnitude = 5400;
            var loadVector = new double[] { 0.551049924, -0.694322904, 0.462881936 };

            var boundaryConditions = new List<InpBoundaryCondition> {new InpBoundaryCondition("IPLATE_BC_NSET", 1, 3)};

            var material = Materials.Titanium;
            var nSetsBoundaryConditions = new Dictionary<string, List<int>> {{"boundarynset", new List<int>() {3, 8, 9, 15, 6, 17, 4, 6}}};
            var nSetsLoad = new Dictionary<string, List<int>>();
            const string nSetLoadName = "loadnset";
            nSetsLoad.Add("loadnset", new List<int>() { 2, 5, 4, 8, 6 });
            var loads = new List<InpLoad>();
            var loadValues = new double[3];
            for (var i = 0; i < 3; i++)
            {
                loadValues[i] = loadMagnitude * loadVector[i] / nSetsLoad[nSetLoadName].Count;
                loads.Add(new InpLoad("IPLATE_LOAD_NSET", i, loadValues[i]));
            }

            var inp = new Inp
            {
                Part = new InpPart(inpPartNodes, inpPartElements, inpPartName, inpPartElementsName, inpPartElementType),
                HeaderLines = new List<string>() {"Generated by IDS Unit Test"},
                InpFile = resources.InpOutputfile,
                Simulation = new InpSimulation
                {
                    BoundaryConditions = boundaryConditions,
                    Material = material,
                    NSetsBoundaryConditions = nSetsBoundaryConditions,
                    NSetsLoad = nSetsLoad,
                    Loads = loads
                }
            };

            inp.Write();

            var actualLines = File.ReadAllLines(inp.InpFile);
            var expectedLines = new string[]
            {
                "*Heading",
                "** Generated by IDS Unit Test",
                "*NODE",
                "1, 42.43426235, 25.42505676, 41.70442496",
                "2, -42.19525282, -20.81917594, -48.76340661",
                "3, -31.9360429, 8.573834545, -27.81285561",
                "4, 49.96204622, -39.79744381, 40.43529585",
                "5, -49.13838234, 26.10712157, -34.94619258",
                "6, -8.733007953, -21.16886775, 33.62122356",
                "7, -26.61676015, -22.89478954, -38.24144866",
                "8, 21.95294674, 15.65370387, -29.30158267",
                "9, 20.01803393, 0.197912162, -7.193738885",
                "10, -4.183780198, -41.24767139, -3.688948005",
                "*ELEMENT, TYPE=C3D4, ELSET=ALL_ELEMENTS",
                "1, 30, 99, 82",
                "2, 37, 86, 91",
                "3, 36, 27, 13",
                "4, 32, 79, 78",
                "5, 33, 67, 84",
                "6, 45, 27, 9",
                "7, 41, 78, 87",
                "8, 94, 98, 5",
                "9, 84, 75, 95",
                "10, 88, 51, 42",
                "*NSET, NSET=boundarynset",
                "3, 8, 9, 15, 6, 17, 4, 6",
                "*NSET, NSET=loadnset",
                "2, 5, 4, 8, 6",
                "*MATERIAL, NAME=Ti4Al6V",
                "*ELASTIC",
                "110000., 0.3",
                "*BOUNDARY",
                "IPLATE_BC_NSET, 1, 3",
                "*Solid Section, material=Ti4Al6V, elset=ALL_ELEMENTS",
                "*Step",
                "*Static",
                "*CLOAD",
                "IPLATE_LOAD_NSET, 0, 595.13391792",
                "*CLOAD",
                "IPLATE_LOAD_NSET, 1, -749.86873632",
                "*CLOAD",
                "IPLATE_LOAD_NSET, 2, 499.91249088",
                "*NODE FILE",
                "U,E",
                "* EL FILE",
                "S",
                "*End Step",
            };

            Assert.AreEqual(expectedLines.Length, actualLines.Length);
            for(var i = 0; i < expectedLines.Length; i++)
            {
                Assert.AreEqual(CleanString(expectedLines[i]), CleanString(actualLines[i]));
            }
        }

        private static string CleanString(string inputString)
        {
            return inputString.ToLower().Trim().Replace(" ", string.Empty);
        }
    }
}
